OUT_DIR := "output"
CORES := '$(if [ "$(uname -s)" = "Darwin" ]; then sysctl -n hw.physicalcpu; elif [ "$(uname -s)" = "Linux" ]; then nproc; fi)'

default:
  @just --list

clean_lualatex: # Clean temporary files generated by Texlab
  find -maxdepth 1 -type d -printf '%f\0' | xargs -0 -P{{CORES}} -I{} sh -c 'if [ -e "{}/master.tex" ]; then cd {}; latexmk -C; fi'

clean_output_dir:
  rm -r {{OUT_DIR}} || true

clean: clean_lualatex clean_output_dir

build: # Building LuaLaTeX object
  find -maxdepth 1 -type d -printf '%f\0' | xargs -0 -P{{CORES}} -I{} sh -c 'if [ -e "{}/master.tex" ]; then cd {}; latexmk -pdflua -halt-on-error master.tex -jobname={} -output-directory=../"{{OUT_DIR}}"; fi'
