name: Build XeLaTeX document
on: [push]
env:
  OUT_DIR: output
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.7
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add findutils font-noto-cjk samurai
            ninja pdf || true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.18
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: notes
          path: ${{ env.OUT_DIR}} /*.pdf
